In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu121


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([2,2])
vector

tensor([2, 2])

In [ ]:
vector.ndim # one square bracket

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim # two square brackets

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
tensor = torch.tensor([[[1,2,3],[3,5,2],[3,5,2]]])
tensor

tensor([[[1, 2, 3],
         [3, 5, 2],
         [3, 5, 2]]])

In [ ]:
tensor.ndim


3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

# Random Tensors

why random numbers?



In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6987, 0.2264, 0.9879, 0.9028],
        [0.6668, 0.4337, 0.3814, 0.5218],
        [0.5726, 0.2869, 0.4174, 0.5314]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_im_tn = torch.rand(3, 224,224)
random_im_tn.shape, random_im_tn.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones


In [ ]:
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating range of tensors and tensor-like

In [ ]:
ran =torch.arange(0,11,2)
ran

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
int_64_tensor = torch.tensor([3,4,5], dtype = None,
                               device = None,
                               requires_grad = False)

int_64_tensor

tensor([3, 4, 5])

In [ ]:
int_64_tensor.dtype

torch.int64

### changing d type of tensors


In [ ]:
float_32_tensor = int_64_tensor.type(torch.float32)
float_32_tensor.dtype

torch.float32

In [ ]:
mul = int_64_tensor * float_32_tensor
mul

tensor([ 9., 16., 25.])

In [ ]:
int_32_tensor = torch.tensor([3,5,8], dtype = torch.int32)
int_32_tensor

tensor([3, 5, 8], dtype=torch.int32)

In [ ]:
# Create a arandom tensor

ran_tensor = torch.rand(3,4)
ran_tensor

tensor([[0.2723, 0.6804, 0.6877, 0.1069],
        [0.4178, 0.9328, 0.3532, 0.6608],
        [0.0847, 0.9551, 0.3939, 0.0727]])

In [ ]:
ran_tensor.max()

tensor(0.9551)

In [ ]:
ran_tensor.shape

torch.Size([3, 4])

In [ ]:
ran_tensor.ndim

2

In [ ]:
ran_tensor.device

device(type='cpu')

### Manipulating Tensors

Tensor Operation inclydes
1. Addition
2. Subtraction
3. Multiplication(element-wise)
4. division
5. Matrix Multiplication(DOT product)

In [ ]:
# Creating a tensor
tensor = torch.randn([1,2,3])
tensor

tensor([[[-0.8432, -0.3177, -2.2715],
         [-0.2076,  1.5315,  0.5010]]])

In [ ]:
tensor + 10 # Element wis eAdiition

tensor([[[ 9.1568,  9.6823,  7.7285],
         [ 9.7924, 11.5315, 10.5010]]])

In [ ]:
tensor * 10 # Element wis emultiplication

tensor([[[ -8.4323,  -3.1765, -22.7154],
         [ -2.0760,  15.3147,   5.0101]]])

In [ ]:
# Try out pytorcvh functions
torch.mul(tensor, 10)

tensor([[[ -8.4323,  -3.1765, -22.7154],
         [ -2.0760,  15.3147,   5.0101]]])

In [ ]:
### MAtrix Multiplication(Dot Product)
# 1. Element wise Matrix mul

tensor1= torch.randn(2,3)
print(f'Tensor 1: {tensor1}')
tensor2 = torch.randn(2,3)
print(f'Tensor 2: {tensor2}')

Tensor 1: tensor([[-1.5489, -0.5228, -0.3234],
        [-0.6818,  0.7554, -0.2602]])
Tensor 2: tensor([[-0.8021, -0.9995, -0.7600],
        [-0.8710,  1.4973, -0.2702]])


In [ ]:
tensor_ele = tensor1 * tensor2
print(f'Element-wise: {tensor_ele}')

Element-wisetensor([[1.2424, 0.5225, 0.2458],
        [0.5939, 1.1310, 0.0703]])


In [ ]:
%%time
tensor_mat_mul = torch.matmul(tensor1, tensor2.T)
print(f'Matrix Multiplication: {tensor_mat_mul}')

Matrix Multiplication: tensor([[ 2.0108,  0.6537],
        [-0.0103,  1.7952]])
CPU times: user 2.72 ms, sys: 2 µs, total: 2.72 ms
Wall time: 2.23 ms


In [ ]:
tensor_mat_mul.shape
tensor_mat_mul.ndim

2

### One of the most common errors in tensor
**Two Rules must follows**
1. The **Inner dimmension**  must match

In [ ]:
tensormul = torch.matmul(torch.rand(3,2), torch.randn(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensormul = torch.matmul(torch.rand(3,2), torch.randn(2,3))
tensormul

tensor([[ 0.8144,  0.7938, -0.1539],
        [ 1.6043,  1.4452, -0.4060],
        [ 0.6952,  0.5263, -0.2625]])

In [ ]:
tensor_A= torch.randn([3,2])
tensor_B = torch.randn([3,2])

tensor_A, tensor_B

(tensor([[-0.9110,  2.1952],
         [-0.6692,  0.0918],
         [ 0.8700, -0.3560]]),
 tensor([[-0.3710,  0.9424],
         [ 0.9013,  0.4198],
         [ 1.2886, -0.1987]]))

In [ ]:
tensor_mul = torch.mm(tensor_A, tensor_B)
tensor_mul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To Fix tensor shape issues we can manipulate by using transpose

In [ ]:
tensor_mul = torch.mm(tensor_A, tensor_B.T)
tensor_mul

tensor([[ 0.2986,  0.2446,  0.4339],
        [ 0.0448, -0.4113, -0.2050],
        [-0.5124,  0.0981, -0.4323]])

In [ ]:
tensor_check = tensor_A.T * tensor_B
tensor_check
## It is not working because it is an elemnt wise multiplication not a matrix multiplicationi

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
tensor_check = torch.mm(tensor_A.T, tensor_B)
tensor_check

tensor([[ 0.8559, -1.3124],
        [-1.1904,  2.1781]])

### finding the min, max, mean, sum etc(tensor aggregation)





In [ ]:
tensor_new = torch.randn([3,2]
                         )
tensor_arrange = torch.arange(0,100,12)
print(tensor_new)
print(tensor_arrange)

tensor([[-0.1632, -1.1786],
        [ 0.3226,  1.9455],
        [ 1.0810, -2.1564]])
tensor([ 0, 12, 24, 36, 48, 60, 72, 84, 96])


In [ ]:
tensor_arrange.dtype


torch.int64

In [ ]:
mean = torch.mean(tensor_arrange)
mean

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
mean = torch.mean(tensor_arrange.type(torch.float32))
mean

tensor(48.)

In [ ]:
sum = torch.sum(tensor_new)
sum

tensor(-0.1493)

In [ ]:
max = torch.max(tensor_new)
max

tensor(1.9455)

### Positional Mean and MAx

####It return the indices

In [ ]:
min = torch.argmax(tensor_arrange)
min

tensor(8)

### Reshaping, Stacking, Squeezing and Unsqueezing

In [ ]:
tensor = torch.arange(12)
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
shape = tensor.shape
shape

torch.Size([12])

In [ ]:
dim = tensor.dim
dim

<function Tensor.dim>

In [ ]:
reshaped_tensor = torch.reshape(tensor,(4,3))
print(reshaped_tensor)
print(reshaped_tensor.shape)
print(reshaped_tensor.ndim)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([4, 3])
2


In [ ]:
tensor_new = torch.randn([4,6])
print(tensor_new)
reshaped_tensor = torch.reshape(tensor_new,(6,4))
print(reshaped_tensor)

tensor([[-0.7158,  2.0058, -0.8480,  1.5450, -0.2875,  0.7387],
        [ 0.2698,  0.5456, -1.2067, -0.4131, -1.6456,  1.5906],
        [ 0.5828,  0.0049,  0.3545, -0.3409, -0.2776,  0.2528],
        [-0.1862, -0.1082, -2.1614,  1.3054, -0.5795,  0.0182]])
tensor([[-0.7158,  2.0058, -0.8480,  1.5450],
        [-0.2875,  0.7387,  0.2698,  0.5456],
        [-1.2067, -0.4131, -1.6456,  1.5906],
        [ 0.5828,  0.0049,  0.3545, -0.3409],
        [-0.2776,  0.2528, -0.1862, -0.1082],
        [-2.1614,  1.3054, -0.5795,  0.0182]])


In [ ]:
import torch
x = torch.rand(3,4)
print(x)
reshaped_tensor = torch.reshape(x,(6,2))
print(reshaped_tensor)

tensor([[0.4012, 0.1549, 0.5140, 0.4841],
        [0.7719, 0.7210, 0.9553, 0.0211],
        [0.2461, 0.6232, 0.8525, 0.7017]])
tensor([[0.4012, 0.1549],
        [0.5140, 0.4841],
        [0.7719, 0.7210],
        [0.9553, 0.0211],
        [0.2461, 0.6232],
        [0.8525, 0.7017]])


In [ ]:
z = x.view(3,4)
z

tensor([[4.0000, 0.1549, 0.5140, 0.4841],
        [4.0000, 0.7210, 0.9553, 0.0211],
        [4.0000, 0.6232, 0.8525, 0.7017]])

In [ ]:
z[:,0]=4
z,x

(tensor([[4.0000, 0.1549, 0.5140, 0.4841],
         [4.0000, 0.7210, 0.9553, 0.0211],
         [4.0000, 0.6232, 0.8525, 0.7017]]),
 tensor([[4.0000, 0.1549, 0.5140, 0.4841],
         [4.0000, 0.7210, 0.9553, 0.0211],
         [4.0000, 0.6232, 0.8525, 0.7017]]))

In [ ]:
stacked_tensor = torch.stack([z,z], dim =0)
stacked_tensor

tensor([[[4.0000, 0.1549, 0.5140, 0.4841],
         [4.0000, 0.7210, 0.9553, 0.0211],
         [4.0000, 0.6232, 0.8525, 0.7017]],

        [[4.0000, 0.1549, 0.5140, 0.4841],
         [4.0000, 0.7210, 0.9553, 0.0211],
         [4.0000, 0.6232, 0.8525, 0.7017]]])

In [ ]:
stacked_tensor.ndim, stacked_tensor.shape

(3, torch.Size([2, 3, 4]))

In [ ]:
reshaped_tensor =torch.reshape(stacked_tensor, shape=(6,4))
reshaped_tensor, reshaped_tensor.ndim, reshaped_tensor.shape

(tensor([[4.0000, 0.1549, 0.5140, 0.4841],
         [4.0000, 0.7210, 0.9553, 0.0211],
         [4.0000, 0.6232, 0.8525, 0.7017],
         [4.0000, 0.1549, 0.5140, 0.4841],
         [4.0000, 0.7210, 0.9553, 0.0211],
         [4.0000, 0.6232, 0.8525, 0.7017]]),
 2,
 torch.Size([6, 4]))

In [ ]:
reshaped_tensor.squeeze()
reshaped_tensor.ndim

2

In [ ]:
q = torch.randn([1,2,1,2,1,2])
q.shape, q.ndim

(torch.Size([1, 2, 1, 2, 1, 2]), 6)

In [ ]:
print(q)

tensor([[[[[[ 0.7686, -1.2906]],

           [[ 1.0194, -1.0894]]]],



         [[[[ 0.8664,  0.6953]],

           [[-0.1118, -0.7503]]]]]])


In [ ]:
squeezed_tensor = q.squeeze()
squeezed_tensor.shape, squeezed_tensor.ndim


(torch.Size([2, 2, 2]), 3)

In [ ]:
print(squeezed_tensor)

tensor([[[ 0.7686, -1.2906],
         [ 1.0194, -1.0894]],

        [[ 0.8664,  0.6953],
         [-0.1118, -0.7503]]])


In [ ]:
unsqueezed = squeezed_tensor.unsqueeze(dim=2)
unsqueezed.shape, unsqueezed.ndim

(torch.Size([2, 2, 1, 2]), 4)

In [ ]:
new_ten = torch.randn([1,2,3])
print(new_ten)
print(new_ten.shape, new_ten.ndim)

tensor([[[-0.9626, -1.4026,  0.6306],
         [-1.4663,  0.9871, -1.4644]]])
torch.Size([1, 2, 3]) 3


In [ ]:
sq = new_ten.squeeze()
sq.shape, sq.ndim
print(sq)

tensor([[-0.9626, -1.4026,  0.6306],
        [-1.4663,  0.9871, -1.4644]])


In [ ]:
per_ten = torch.permute(new_ten, (2,0,1))
print(per_ten)


tensor([[[-0.9626, -1.4663]],

        [[-1.4026,  0.9871]],

        [[ 0.6306, -1.4644]]])


### Indexing with Pytorch
*Indexing with pytorch is similar to indexing with numpy*

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
y = torch.randn([2,3,3])
print(y)
##  (2 batches, 3 rows, 3 columns),

tensor([[[ 1.7705,  0.1768, -1.3673],
         [ 0.4915, -0.5418,  0.1430],
         [-0.5324, -0.2449,  1.0064]],

        [[-1.1235, -0.0676,  0.5837],
         [-0.2435,  0.4311,  0.8199],
         [ 0.8219,  1.3867, -0.0383]]])


tensor([ 1.7705, -1.1235])

In [ ]:
# 1st bracket
for i in range(3):
 print(f"{i}Row: {y[i]}")

0Row: tensor([[ 0.1803, -1.2384,  1.2504],
        [-0.7269,  1.1187, -0.7244],
        [-1.1754, -1.2711, -0.2485]])
1Row: tensor([[ 0.3018,  0.3445, -1.4418],
        [ 0.5260,  1.3122,  2.0953],
        [ 1.1241, -1.3597,  0.4734]])


IndexError: index 2 is out of bounds for dimension 0 with size 2

In [ ]:
# index om the middle bracket (dim=1)
for i in range(2):
  for j in range(3):
    print(f"{j}Row: {y[i][j]}")

0Row: tensor([ 0.1803, -1.2384,  1.2504])
1Row: tensor([-0.7269,  1.1187, -0.7244])
2Row: tensor([-1.1754, -1.2711, -0.2485])
0Row: tensor([ 0.3018,  0.3445, -1.4418])
1Row: tensor([0.5260, 1.3122, 2.0953])
2Row: tensor([ 1.1241, -1.3597,  0.4734])


In [ ]:
y[0][0][0] # indexing on thr most inner bracket(dim =last dimension)

tensor(0.1803)

In [ ]:
for i in range(2):
  for j in range(3):
    for k in range(3):
      print(f'{y[i][j][k]}')

0.18025457859039307
-1.2384194135665894
1.250357747077942
-0.7268917560577393
1.1186509132385254
-0.7243580222129822
-1.1754014492034912
-1.2710700035095215
-0.24851427972316742
0.3018139600753784
0.34452277421951294
-1.4418343305587769
0.5260282754898071
1.312209129333496
2.095349073410034
1.1241401433944702
-1.359706997871399
0.4734387695789337


In [ ]:
flatten_arra = torch.flatten(y, start_dim=0)
flatten_arra
mean = torch.mean(flatten_arra)

for i in range(len(flatten_arra)):
  print(f'{(flatten_arra[i])**2/mean}')

1.0819164514541626
51.06890869140625
52.05826187133789
17.59383773803711
41.66872787475586
17.471397399902344
46.003780364990234
53.797245025634766
2.056476593017578
3.033190965652466
3.952364206314087
69.22322082519531
9.213809967041016
57.335975646972656
146.19544982910156
42.078670501708984
61.56186294555664
7.463606357574463


In [ ]:
x = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x.shape, x.ndim

(torch.Size([1, 3, 3]), 3)

In [ ]:
x[0,:,2]

tensor([3, 6, 9])

In [ ]:
i = torch.randn(size=(2,3,4))
print(i)

tensor([[[ 1.7220, -0.1859, -1.8682, -1.9991],
         [ 0.6892, -0.7655, -0.6550, -1.3411],
         [-0.4258,  0.4360,  0.2970, -1.1793]],

        [[-0.9444, -0.4136,  0.4409, -1.6386],
         [ 2.1371, -0.2172,  0.4650, -0.9120],
         [-1.3756,  0.2693,  1.7429, -1.2157]]])


In [ ]:
i[:,:,0]

tensor([[ 1.7220,  0.6892, -0.4258],
        [-0.9444,  2.1371, -1.3756]])

In [ ]:
i[0,2,3]

tensor(-1.1793)

In [ ]:
i[1,:,2]

tensor([0.4409, 0.4650, 1.7429])

In [ ]:
j = torch.randn(size=(2,3,3,3))
j

tensor([[[[-0.9468,  0.4277, -0.3818],
          [ 0.6283,  1.2610,  1.3978],
          [ 0.6735,  0.3187,  0.1436]],

         [[ 1.9720, -0.3869,  0.1213],
          [-0.9806, -1.2463, -0.8166],
          [ 0.3857,  0.7484, -1.7356]],

         [[-2.4910, -0.8207,  0.4536],
          [ 0.8704,  0.4535, -0.4437],
          [-1.0318, -1.4526,  1.2911]]],


        [[[-0.8942, -0.0486,  1.3410],
          [-0.5093, -0.6133, -0.2152],
          [ 0.5478,  0.1613,  0.2563]],

         [[-1.1689,  0.0845,  0.7754],
          [-0.3096,  1.5533, -0.2906],
          [-2.5274,  0.2031, -0.0383]],

         [[-0.4654, -1.6795,  0.9278],
          [-0.3788,  0.5507,  2.7754],
          [ 1.3937,  0.1350,  0.9804]]]])

In [ ]:
j[:,:,0,0]

tensor([[-0.9468,  1.9720, -2.4910],
        [-0.8942, -1.1689, -0.4654]])

### Numpy array to tensor

In [ ]:
import torch
import numpy as np

In [ ]:
array = np.arange(1,10)
print(array,array.ndim, array.dtype)
tensor = torch.from_numpy(array).type(torch.float32)# to change the numpy array dtype to
print(tensor, tensor.ndim, tensor.shape, tensor.dtype)

[1 2 3 4 5 6 7 8 9] 1 int64
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) 1 torch.Size([9]) torch.float32


In [ ]:
tensor = torch.randn(5)
tensor
numpy_array = tensor.numpy()
numpy_array

array([-2.2693584 , -2.4540472 , -0.5082112 , -0.32308063, -1.1927376 ],
      dtype=float32)

##Reproducibility (trying to takeout of random)
To reduce the randomness in NN and PyTorch comes the conceptd of a random seed.

In [ ]:
# creating two random tensors
import torch
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)
print(tensor_A)
print(tensor_B)


tensor([[0.4860, 0.0511, 0.8335, 0.4864],
        [0.4071, 0.1214, 0.5907, 0.6638],
        [0.3801, 0.0677, 0.7697, 0.8230]])
tensor([[0.7572, 0.7322, 0.6506, 0.8527],
        [0.9452, 0.6409, 0.9923, 0.5977],
        [0.8238, 0.4401, 0.4815, 0.9315]])


In [ ]:
# now lets make reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(42)
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)
print(tensor_A)
print(tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


###Running Tensors and Pytorch objects on gpu

#### Getting a GPU
1. Easiest - USe google colab for a free GPU
2. Use your own GPU
3. Use cloud Computing - GCP, AWS, Azure, these services allow you to rent computters on the cloud and access them.

In [ ]:
!nvidia-smi


Sun Dec 15 14:56:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#### Setup device agnostic code

In [2]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

#### Putting tensor and models in GPU

In [4]:
tensor = torch.randn(3,4)
print(tensor)
print(tensor.device)

tensor([[-0.3199, -0.3176, -0.7016, -0.4440],
        [-2.5829, -1.7952,  1.7227, -0.1779],
        [ 0.5199,  2.9969, -1.2961, -1.5805]])
cpu


In [5]:
# Moving tensor to GPU
tensor_to_gpu = tensor.to(device)
print(tensor_to_gpu.device)

cuda:0


#### Tensors back to CPU(NUMPY)

In [7]:
# moving tensors back to cpu
tensor_to_CPU = tensor_to_gpu.cpu().numpy()
print(tensor_to_CPU)

[[-0.31993818 -0.31757542 -0.7015936  -0.44400254]
 [-2.5829105  -1.7952023   1.722718   -0.17789708]
 [ 0.519911    2.9969227  -1.2961372  -1.5804735 ]]


### Excercise

In [10]:
# 1 Create a random tensor of shape(7,7)
import torch
random_tensor = torch.randn(size=(7,7))
print(random_tensor)
print(random_tensor.shape)

tensor([[ 0.3863, -0.4190, -1.6738, -1.4302, -0.2610, -1.6664,  1.0021],
        [ 0.9629,  0.5947, -0.0136, -1.0976,  0.9474, -1.0177,  0.6805],
        [ 2.4335, -0.6583,  0.8647, -1.2381, -0.0854,  0.8531,  0.8360],
        [ 0.2645,  1.1771,  0.2340, -0.9899, -0.9934, -0.7657, -1.0873],
        [ 1.0459, -2.3482,  0.2357,  1.2546, -0.3370,  1.9403, -0.8663],
        [-0.8611, -0.2434,  0.2305, -0.9527, -1.1874,  1.5589,  0.5384],
        [ 0.9637, -2.0457,  0.0615, -0.5781,  1.1086, -2.1073, -0.8267]])
torch.Size([7, 7])


In [14]:
# Perform a matrix multiplication on the tensor from 2 with another random
# tensor with shape (1,7)
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
new_tensor = torch.randn(size=(1,7))
random_tensor = torch.randn(size=(7,7))
print(new_tensor)
print(new_tensor.shape)

print("MAtrix Multiplication")
mul = torch.mm(random_tensor, new_tensor.T)
print(mul)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986,  0.4033]])
torch.Size([1, 7])
MAtrix Multiplication
tensor([[-0.9825],
        [ 2.3102],
        [ 3.4249],
        [-1.4673],
        [ 2.3200],
        [-6.1373],
        [ 1.5235]])


In [15]:
Random_SEED_GPU = 1234
torch.cuda.manual_seed(Random_SEED_GPU)
new_tensor_gpu = torch.randn(size=(1,7)).to(device)
random_tensor_gpu = torch.randn(size=(7,7)).to(device)


print("MAtrix Multiplication")
mul_gpu = torch.mm(random_tensor_gpu, new_tensor_gpu.T)
print(mul_gpu)

MAtrix Multiplication
tensor([[-0.6415],
        [-2.0764],
        [ 0.2977],
        [ 0.0253],
        [-1.5636],
        [-0.5572],
        [ 1.1076]], device='cuda:0')


In [31]:
#Accessing GPu
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
torch.cuda.is_available()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

new_tensor_A = torch.randn(size=(2,3))
new_tensor_B = torch.randn(size=(2,3))
print(new_tensor_A)
print(new_tensor_B)
print('\n')
gpu_tensor_A, gpu_tensor_B = new_tensor_A.to(device), new_tensor_B.to(device)
print(gpu_tensor_A)
print(gpu_tensor_B)
print('\nMATRIXMULL \n')
mul = torch.mm(gpu_tensor_A, gpu_tensor_B.T)
print(mul)
print(mul.device)

print('\n MAX')
max = torch.max(mul)
print(max)

print('\n Min')

min = torch.min(mul)
print(min)


cuda
tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])
tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])


tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]], device='cuda:0')
tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]], device='cuda:0')

MATRIXMULL 

tensor([[ 0.7695,  0.3487],
        [ 1.1390, -0.6898]], device='cuda:0')
cuda:0

 MAX
tensor(1.1390, device='cuda:0')

 Min
tensor(-0.6898, device='cuda:0')
